name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.COMMIT}}
      USER_NAME   : outsider987
      USER_EMAIL  : t7902195204@gmail.com
      PUBLISH_DIR : ./dist
      API_URL     : ${{secrets.API_URL}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install 
      run: |
       npm install --legacy-peer-deps
    - name: npm run build
      run: |
        npm run build
    - name: Echo secrets.COMMIT
      run: |
        echo "The value of secrets.COMMIT is ${{secrets.COMMIT}} "
    - name: Echo secrets.API_URL
      run: |
        echo "The value of secrets.API_URL is ${{secrets.API_URL}} "

    - name: Commit dist to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.COMMIT }}
        BRANCH: gh-pages
        FOLDER: dist
  
